// Unidades añadidas al temario del artifact para cubrir la especificación A2–B2
// (mismo formato que grammarContent.js).

export const EXTRA_UNITS = [
/* ---------- A2 ---------- */
{id:"u34",lv:"A2",t:"Question words",s:"what, where, when, who, why, how…",
 when:["Orden: <b>palabra interrogativa + auxiliar + sujeto + verbo</b>: <i>Where do you live?</i>","Con to be no hace falta do: <i>Where is the station?</i>","Si la palabra interrogativa es el <b>sujeto</b>, no se usa do: <i>Who called you?</i>","<b>How</b> + adjetivo o adverbio: how much, how many, how long, how often, how old, how far."],
 f:["Question word","+","do / does / did / be","+","sujeto","+","verbo"],
 tbl:{h:["Palabra","Pregunta por","Ejemplo"],r:[["What","cosa, información","What do you do?"],["Where","lugar","Where does she work?"],["When","momento","When did you arrive?"],["Who","persona","Who is your teacher?"],["Why","motivo","Why are you late?"],["Which","elección entre opciones","Which bus goes to the centre?"],["Whose","posesión","Whose bag is this?"],["How","modo","How do you make bread?"],["How often","frecuencia","How often do you train?"],["How long","duración","How long have you lived here?"]]},
 ex:[["What do you do? — I'm a baker.","¿A qué te dedicas? — Soy panadero."],["How often do you go to the gym?","¿Cada cuánto vas al gimnasio?"],["Who told you that?","¿Quién te dijo eso?"],["Which one do you prefer?","¿Cuál prefieres?"]],
 err:[["Where you live?","Where do you live?","Falta el auxiliar do."],["What means this word?","What does this word mean?","Con verbos normales: do/does + verbo sin -s."],["Who did call you?","Who called you?","Si who es el sujeto, sin did."],["How many money?","How much money?","Money es incontable → much."]],
 tip:"<b>What do you do?</b> pregunta por tu trabajo, no por lo que haces ahora mismo (<i>What are you doing?</i>).",
 q:[["___ do you live? (lugar)",["where"]],["___ does this word mean?",["what"]],["How ___ do you go swimming? (frecuencia)",["often"]],["___ bag is this? (de quién)",["whose"]],["___ did you arrive? (cuándo)",["when"]],{q:"¿Quién te llamó?",o:["Who did call you?","Who called you?","Who you called?"],a:1,why:"Who es el sujeto: sin did."}]},

/* ---------- B1 ---------- */
{id:"u35",lv:"B1",t:"Cuantificadores",s:"a few, a little, few, little, several, plenty of, enough, too",
 tbl:{h:["Con contables","Con incontables","Significado"],r:[["a few","a little","algunos, un poco (suficiente)"],["few","little","pocos, poco (casi nada)"],["several","—","varios"],["many / a lot of","much / a lot of","muchos, mucho"],["plenty of","plenty of","de sobra"],["enough","enough","suficiente(s)"],["too many","too much","demasiados, demasiado"]]},
 notes:["<b>enough</b> va <b>antes del sustantivo</b> (<i>enough time</i>) pero <b>después del adjetivo</b> (<i>old enough</i>).","<b>too</b> + adjetivo = demasiado: <i>too expensive</i>. Nunca <i>too much expensive</i>."],
 ex:[["I have a few friends in London.","Tengo algunos amigos en Londres."],["Few people know this.","Poca gente lo sabe."],["There's too much sugar in this cake.","Este pastel tiene demasiado azúcar."],["He isn't old enough to drive.","No tiene edad suficiente para conducir."]],
 err:[["I have a little friends.","I have a few friends.","Friends es contable → a few."],["There are too much cars.","There are too many cars.","Contable → too many."],["It's too much expensive.","It's too expensive.","Too + adjetivo, sin much."],["enough old","old enough","Enough va detrás del adjetivo."]],
 tip:"<b>a few / a little</b> suenan positivos (hay algo); <b>few / little</b> suenan negativos (casi nada): <i>I have a little money</i> (algo tengo) / <i>I have little money</i> (casi no tengo).",
 q:[["I have ___ friends in London. (algunos)",["a few"]],["There's ___ milk left. Can you buy some? (poca, casi nada)",["little","very little"]],["There are ___ cars in the city centre. (demasiados)",["too many"]],["She isn't old ___ to drive.",["enough"]],["Don't worry, we have ___ of time. (de sobra)",["plenty"]],{q:"It's ___ expensive for me.",o:["too much","too","enough"],a:1}]},

{id:"u36",lv:"B1",t:"Phrasal verbs",s:"Verbo + partícula con significado propio",
 when:["Un phrasal verb es verbo + partícula (up, out, off, on…) y a menudo su significado no se deduce: <i>give up</i> = rendirse, dejar.","En el inglés hablado se usan mucho más que sus sinónimos formales: <i>find out</i> en vez de <i>discover</i>.","Apréndelos como vocabulario, con una frase de ejemplo (y añádelos a tus palabras)."],
 tbl:{h:["Phrasal verb","Significado","Ejemplo"],r:[["get up","levantarse","I get up at six."],["give up","rendirse / dejar (un hábito)","I gave up smoking."],["find out","descubrir, enterarse","I found out the truth."],["look for","buscar","I'm looking for my keys."],["look after","cuidar","She looks after her grandmother."],["look forward to","tener ganas de","I look forward to seeing you."],["turn on / off","encender / apagar","Turn off the light."],["put off","aplazar","They put off the meeting."],["run out of","quedarse sin","We've run out of milk."],["carry on","continuar","Carry on, please."],["take off","despegar / quitarse (ropa)","The plane took off late."],["get on with","llevarse bien con","I get on well with my boss."]]},
 notes:["<b>Separables</b>: el objeto puede ir en medio o al final: <i>turn off the light / turn the light off</i>. Si es un <b>pronombre</b>, va obligatoriamente en medio: <i>turn it off</i>.","<b>Inseparables</b>: el objeto siempre va detrás: <i>look after the children</i>, <i>look after them</i>.","Después de preposición, verbo en <b>-ing</b>: <i>look forward to seeing</i>."],
 ex:[["I gave up smoking two years ago.","Dejé de fumar hace dos años."],["Can you turn it off, please?","¿Puedes apagarlo, por favor?"],["We've run out of bread.","Nos hemos quedado sin pan."],["I'm looking forward to the holidays.","Tengo ganas de que lleguen las vacaciones."]],
 err:[["Turn off it.","Turn it off.","Con pronombre, en medio."],["I look forward to see you.","I look forward to seeing you.","To es preposición → -ing."],["I'm looking my keys.","I'm looking for my keys.","Buscar = look for."],["We run out milk.","We've run out of milk.","Run out + of + cosa."]],
 q:[["Don't ___ up! You're almost there. (rendirse)",["give"]],["The radio is too loud. Can you turn ___ off?",["it"]],["We've run out ___ milk.",["of"]],["She looks ___ her little brother after school. (cuidar)",["after"]],["I found ___ the truth yesterday. (enterarse)",["out"]],{q:"I'm looking forward to ___ you.",o:["see","seeing","saw"],a:1}]},

/* ---------- B2 ---------- */
{id:"u37",lv:"B2",t:"Conectores",s:"however, although, despite, whereas, therefore…",
 when:["Los conectores dan orden y lógica al texto: en el <b>Writing</b> del B2 First cuentan mucho para la nota.","Fíjate en qué va detrás de cada uno: una <b>frase completa</b> o un <b>sustantivo / -ing</b>."],
 tbl:{h:["Función","Conector","Qué va detrás","Ejemplo"],r:[["Contraste","although / even though","frase","Although it was cold, we went out."],["Contraste","despite / in spite of","sustantivo o -ing","Despite the cold, we went out."],["Contraste","however / nevertheless","nueva frase (tras punto)","It was cold. However, we went out."],["Contraste","whereas / while","frase (compara dos cosas)","I like tea, whereas my wife prefers coffee."],["Añadir","moreover / furthermore / in addition","nueva frase","It's cheap. Moreover, it's healthy."],["Consecuencia","therefore / as a result / consequently","nueva frase","It rained. As a result, the match was cancelled."],["Finalidad","so that / in order to","frase / verbo","I left early in order to catch the train."],["Concluir","in conclusion / to sum up","nueva frase","In conclusion, I believe that…"]]},
 ex:[["Despite being tired, she finished the essay.","A pesar de estar cansada, terminó el essay."],["The flat is small. However, it's very central.","El piso es pequeño. Sin embargo, es muy céntrico."],["Although it's expensive, it's worth it.","Aunque es caro, vale la pena."]],
 err:[["Despite it was cold…","Although it was cold… / Despite the cold…","Despite + sustantivo o -ing, nunca una frase."],["Despite of the rain","Despite the rain / In spite of the rain","Despite nunca lleva of."],["However it was cold, we went out.","Although it was cold, we went out.","However no une dos frases: va tras punto y con coma."],["Although it was late, but we stayed.","Although it was late, we stayed.","No uses although y but juntos."]],
 tip:"Truco para el First: en cada essay usa al menos un conector de <b>contraste</b>, uno para <b>añadir</b> y uno para <b>concluir</b>.",
 q:[["___ it was raining, we went for a walk. (aunque)",["although","even though","though"]],["___ the rain, we went for a walk. (a pesar de)",["despite","in spite of"]],["The hotel was cheap. ___, it was very clean. (además)",["moreover","furthermore","in addition","what is more"]],["I like the city, ___ my sister prefers the countryside. (mientras que)",["whereas","while"]],["It rained a lot. As a ___, the match was cancelled.",["result"]],{q:"___ being tired, he kept working.",o:["Although","Despite","However"],a:1,why:"Despite + -ing."}]},

{id:"u38",lv:"B2",t:"Subjuntivo en inglés",s:"I suggest that he take…, It's important that…",
 when:["Tras verbos de <b>sugerencia u obligación</b> (suggest, recommend, insist, demand, propose) + <b>that</b>, el verbo va en forma base para todas las personas: <i>I suggest that he <b>take</b> a break.</i>","Tras <b>It's important / essential / vital / necessary that</b>: <i>It's essential that everyone <b>be</b> on time.</i>","En inglés británico también se usa <b>should</b>: <i>I suggest that he should take a break.</i>","Otra opción muy común: suggest + <b>-ing</b>: <i>I suggest taking a break.</i>"],
 f:["suggest / recommend / insist","+","that","+","sujeto","+","verbo base"],
 ex:[["The doctor recommended that she rest for a week.","El médico le recomendó que descansara una semana."],["It's vital that he be informed.","Es vital que se le informe."],["I suggest going by train.","Sugiero ir en tren."]],
 err:[["I suggest you to go.","I suggest (that) you go. / I suggest going.","Suggest nunca va con to + verbo."],["It's important that he is on time.","It's important that he be on time.","En registro formal (y en el examen), forma base."],["She insisted that he pays.","She insisted that he pay.","Sin -s: forma base."]],
 tip:"Es una estructura de registro <b>formal</b>: úsala en essays y emails formales; en una conversación normal no hace falta.",
 q:[["I suggest that he ___ a break. (take)",["take","should take"]],["It's essential that everyone ___ on time. (be)",["be","should be"]],["The doctor recommended that she ___ for a week. (rest)",["rest","should rest"]],["I suggest ___ by train. (go)",["going"]],{q:"¿Cuál es correcta?",o:["I suggest you to call her.","I suggest that you call her.","I suggest you calling her."],a:1}]},
];
