// Estructuras que detecta el analizador (Frases y Cuaderno) → nombre y unidad del temario.
// El nivel se toma de la unidad (src/lib/grammar.js), así hay un solo temario en toda la app.

export const DETECTIONS = {
  'verb-to-be': { name: 'Verb to be', unit: 'u1' },
  'there-is-are': { name: 'There is / there are', unit: 'u4' },
  'present-simple': { name: 'Present simple', unit: 'u5' },
  'present-continuous': { name: 'Present continuous', unit: 'u7' },
  'past-simple': { name: 'Past simple', unit: 'u9' },
  'countable-uncountable': { name: 'Countable / uncountable', unit: 'u10' },
  comparatives: { name: 'Comparativos y superlativos', unit: 'u11' },
  'going-to': { name: 'Futuro: going to', unit: 'u12' },
  will: { name: 'Futuro: will', unit: 'u12' },
  'question-words': { name: 'Question words', unit: 'u34' },
  'past-continuous': { name: 'Past continuous', unit: 'u14' },
  'present-perfect': { name: 'Present perfect', unit: 'u15' },
  'basic-modals': { name: 'Modales (must, should, have to…)', unit: 'u17' },
  'zero-conditional': { name: 'Zero conditional', unit: 'u18' },
  'first-conditional': { name: 'First conditional', unit: 'u18' },
  'second-conditional': { name: 'Second conditional', unit: 'u18' },
  'passive-basic': { name: 'Voz pasiva', unit: 'u19' },
  'passive-advanced': { name: 'Pasiva con modales o tiempos perfectos', unit: 'u19' },
  'relative-defining': { name: 'Relative clauses (defining)', unit: 'u20' },
  'relative-non-defining': { name: 'Relative clauses (non-defining)', unit: 'u20' },
  'gerund-infinitive': { name: 'Gerundio o infinitivo', unit: 'u21' },
  quantifiers: { name: 'Cuantificadores', unit: 'u35' },
  'phrasal-verbs': { name: 'Phrasal verbs', unit: 'u36' },
  'present-perfect-continuous': { name: 'Present perfect continuous', unit: 'u22' },
  'past-perfect': { name: 'Past perfect', unit: 'u23' },
  'past-perfect-continuous': { name: 'Past perfect continuous', unit: 'u23' },
  'third-conditional': { name: 'Third conditional', unit: 'u24' },
  'mixed-conditionals': { name: 'Mixed conditional', unit: 'u24' },
  'reported-speech-basic': { name: 'Reported speech', unit: 'u25' },
  'reported-speech-advanced': { name: 'Reported speech (preguntas, órdenes…)', unit: 'u25' },
  'probability-modals': { name: 'Modales de probabilidad', unit: 'u26' },
  'past-deduction-modals': { name: 'Modales de deducción en pasado', unit: 'u26' },
  'used-to': { name: 'Used to', unit: 'u27' },
  'be-used-to': { name: 'be / get used to', unit: 'u27' },
  wish: { name: 'Wish / if only', unit: 'u28' },
  'future-perfect': { name: 'Future perfect', unit: 'u29' },
  'advanced-connectors': { name: 'Conectores avanzados', unit: 'u37' },
  subjunctive: { name: 'Subjuntivo', unit: 'u38' },
  inversion: { name: 'Inversión', unit: 'u30' },
  'cleft-sentences': { name: 'Cleft sentences', unit: 'u31' },
  'participle-clauses': { name: 'Participle clauses', unit: 'u32' },
  causative: { name: 'Causativa (have something done)', unit: 'u33' },
};

// Para análisis guardados antes de enlazar con el temario: su unidad a partir del id detectado.
export const unitOfDetection = (topicId) => DETECTIONS[topicId]?.unit ?? null;
